pull_request_rules:
  # Auto-merge for develop branch
  - name: "ðŸ”„ Auto-merge to develop branch"
    conditions:
      - base=develop
      - "#approved-reviews-by>=1"
      - "check-success=Java CI with Maven"  # Matches your GitHub Actions job name
      - "label!=work-in-progress"
      - "label!=do-not-merge"
      - "#conflicts=0"
    actions:
      merge:
        method: squash
        strict: smart
        commit_message_template: |
          {{title}} (#{{number}})
          
          {{body}}
      delete_head_branch: {}
      comment:
        message: |
          âœ… This pull request has been automatically merged to develop!

  # Auto-merge for main branch (production releases)
  - name: "ðŸš€ Auto-merge to main branch"
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "check-success=Java CI with Maven"
      - "label=release-ready"
      - "#conflicts=0"
    actions:
      merge:
        method: merge
        strict: smart
        commit_message_template: |
          {{title}} (#{{number}})
          
          {{body}}
      delete_head_branch: {}
      comment:
        message: |
          ðŸŽ‰ This pull request has been automatically merged to main!

  # Auto-request reviews for new PRs
  - name: "ðŸ‘¥ Auto-request reviews"
    conditions:
      - "#review-requested=0"
      - "#approved-reviews-by=0"
      - "author!=Trividha13"
    actions:
      request_reviews:
        users:
          - Trividha13

  # Label feature branches automatically
  - name: "ðŸ·ï¸ Label feature PRs"
    conditions:
      - "head~=^feature/"
    actions:
      label:
        add:
          - "type:feature"
          - "status:review-needed"

  # Label hotfix branches with high priority
  - name: "ðŸš¨ Label hotfix PRs"
    conditions:
      - "head~=^hotfix/"
    actions:
      label:
        add:
          - "type:hotfix"
          - "priority:high"

  # Auto-rebase when develop is updated
  - name: "ðŸ”„ Auto-rebase PRs targeting develop"
    conditions:
      - base=develop
      - "#conflicts=0"
      - "label=autorebase"
    actions:
      rebase: {}

queue_rules:
  # Merge queue for develop branch
  - name: develop-queue
    conditions:
      - base=develop
      - "#approved-reviews-by>=1"
      - "check-success=Java CI with Maven"
    queue_conditions:
      - "check-success=Java CI with Maven"
    
  # Main branch merge queue
  - name: main-queue
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "check-success=Java CI with Maven"
      - "label=release-ready"
    queue_conditions:
      - "check-success=Java CI with Maven"
