pull_request_rules:
  # Auto-merge for develop branch
  - name: "🔄 Auto-merge to develop branch"
    conditions:
      - base=develop
      - "#approved-reviews-by>=1"
      - "check-success=build"  # This should match your GitHub Actions job name
      - "label!=work-in-progress"
      - "label!=do-not-merge"
      - "-conflict"  # Fixed: removed # and changed to -conflict
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{title}} (#{{number}})
          
          {{body}}
      delete_head_branch: {}
      comment:
        message: |
          ✅ This pull request has been automatically merged to develop!

  # Auto-merge for main branch (production releases)
  - name: "🚀 Auto-merge to main branch"
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "check-success=build"
      - "label=release-ready"
      - "-conflict"  # Fixed: removed # and changed to -conflict
    actions:
      merge:
        method: merge
        commit_message_template: |
          {{title}} (#{{number}})
          
          {{body}}
      delete_head_branch: {}
      comment:
        message: |
          🎉 This pull request has been automatically merged to main!

  # Auto-request reviews for new PRs
  - name: "👥 Auto-request reviews"
    conditions:
      - "#review-requested=0"
      - "#approved-reviews-by=0"
      - "author!=Trividha13"
    actions:
      request_reviews:
        users:
          - Trividha13

  # Label feature branches automatically
  - name: "🏷️ Label feature PRs"
    conditions:
      - "head~=^feature/"
    actions:
      label:
        add:
          - "type:feature"
          - "status:review-needed"

  # Label hotfix branches with high priority
  - name: "🚨 Label hotfix PRs"
    conditions:
      - "head~=^hotfix/"
    actions:
      label:
        add:
          - "type:hotfix"
          - "priority:high"

  # Auto-rebase when develop is updated
  - name: "🔄 Auto-rebase PRs targeting develop"
    conditions:
      - base=develop
      - "-conflict"  # Fixed: removed # and changed to -conflict
      - "label=autorebase"
    actions:
      rebase: {}

queue_rules:
  # Merge queue for develop branch
  - name: develop-queue
    conditions:
      - base=develop
      - "#approved-reviews-by>=1"
      - "check-success=build"
    
  # Main branch merge queue
  - name: main-queue
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "check-success=build"
      - "label=release-ready"
