pull_request_rules:
  - name: Automatic merge for develop branch
    conditions:
      - base=develop
      - "#approved-reviews-by>=1"
      - "status-success=Java CI with Maven"
      - "label!=do-not-merge"
      - "-conflict"
    actions:
      merge:
        method: merge
      delete_head_branch: {}
  - name: Automatic merge for main branch  
    conditions:
      - base=main
      - "#approved-reviews-by>=2"
      - "status-success=Java CI with Maven"
      - "-conflict"
    actions:
      merge:
        method: merge
      delete_head_branch: {}
  - name: Add feature label
    conditions:
      - head~=^feature/
    actions:
      label:
        add: ["feature"]
  - name: Add bugfix label
    conditions:
      - head~=^bugfix/
    actions:
      label:
        add: ["bugfix"]
  - name: Request review for features
    conditions:
      - head~=^feature/
      - "#review-requested=0"
    actions:
      request_reviews:
        users: ["Trividha13"]
  - name: Auto-label based on files
    conditions:
      - files~=\.java$
    actions:
      label:
        add: ["java"]
